services:
  app:
    build: ./conf/web
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
  postgres:
    image: postgres:14.7-alpine3.17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passw@rd
      POSTGRES_DB: laravel
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
  node:
    image: node:lts-alpine
    working_dir: /var/www/html
    ports:
      - 5173:5173
    volumes:
      - ./app:/var/www/html
    command: sh -c "cd /var/www/html && npm run dev"
volumes:
  postgresql: